- hosts: localhost
  vars:
    home: '/home/jek'
    gopath: '/usr/local/go/bin/go'

  tasks:
    - name: Install packages
      become: yes
      package:
        name: '{{ item }}'
        state: present
      loop:
        - zsh
        - htop
        - gnome-tweak-tool
        - gnome-extensions-app
        - fira-code-fonts
        - neovim
        - bat
        - exa
        - fzf
        - git-delta
        - ripgrep
        - fd-find
    - name: Install starship
      ansible.builtin.shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
    - name: Install jump
      ansible.builtin.shell: '{{ gopath }} install github.com/gsamokovarov/jump@latest'
    - name: Install fnm
      ansible.builtin.shell: 'curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell'
    - name: Create config folders
      file:
        path: '{{ item }}'
        state: directory
        recurse: yes
      loop:
        - '{{ home }}/.config/nvim'
    - name: Set up config symlinks
      file:
        src: '{{ playbook_dir }}/{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
      with_items:
          - { src: 'starship.toml', dest: '{{ home }}/.config/starship.toml'}
          - { src: '.gitconfig', dest: '{{ home }}/.gitconfig'}
          - { src: 'init.vim', dest: '{{ home }}/.config/nvim/init.vim'}
          - { src: '.zshrc', dest: '{{ home }}/.zshrc'}
