---
- hosts: localhost
  connection: local
  vars:
    user: 'jek'
    home: '/home/{{ user }}'
    gopath: '/usr/local/go/bin/go'

  tasks:
    - name: Install packages
      become: yes
      package:
        name: '{{ item }}'
        state: present
      loop:
        - zsh
        - htop
        - gnome-tweak-tool
        - gnome-extensions-app
        - fira-code-fonts
        - neovim
        - bat
        - exa
        - fzf
        - git-delta
        - ripgrep
        - fd-find
        - g++
    - name: Install starship
      ansible.builtin.shell: sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
    - name: Install jump
      ansible.builtin.shell: '{{ gopath }} install github.com/gsamokovarov/jump@latest'
    - name: Install fnm
      ansible.builtin.shell: 'curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell'
    - name: Install sdkman
      ansible.builtin.shell: 'curl -s "https://get.sdkman.io" | bash'
    - name: Create config folders
      file:
        path: '{{ item }}'
        state: directory
        recurse: yes
        owner: '{{ user }}'
      loop:
        - '{{ home }}/.config/nvim'
        - '{{ home }}/.config/nvim/lua'
        - '{{ home }}/.config/nvim/lua/config'
    - name: Set up config symlinks
      file:
        src: '{{ playbook_dir }}/{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        owner: '{{ user }}'
      with_items:
          - { src: 'starship.toml', dest: '{{ home }}/.config/starship.toml'}
          - { src: '.gitconfig', dest: '{{ home }}/.gitconfig'}
          - { src: 'nvim/init.lua', dest: '{{ home }}/.config/nvim/init.lua'}
          - { src: 'nvim/lua/options.lua', dest: '{{ home }}/.config/nvim/lua/options.lua'}
          - { src: 'nvim/lua/plugins.lua', dest: '{{ home }}/.config/nvim/lua/plugins.lua'}
          - { src: 'nvim/lua/autocmd.lua', dest: '{{ home }}/.config/nvim/lua/autocmd.lua'}
          - { src: 'nvim/lua/mappings.lua', dest: '{{ home }}/.config/nvim/lua/mappings.lua'}
          - { src: 'nvim/lua/config/treesitter.lua', dest: '{{ home }}/.config/nvim/lua/config/treesitter.lua'}
          - { src: 'nvim/lua/config/lsp.lua', dest: '{{ home }}/.config/nvim/lua/config/lsp.lua'}
          - { src: 'nvim/lua/config/lsp-installer.lua', dest: '{{ home }}/.config/nvim/lua/config/lsp-installer.lua'}
          - { src: 'nvim/lua/config/nvim-tree.lua', dest: '{{ home }}/.config/nvim/lua/config/nvim-tree.lua'}
          - { src: '.zshrc', dest: '{{ home }}/.zshrc'}

